#!/usr/bin/env bash
# Bash script that will display information about subdomains
# shellcheck disable=SC2086

dom_and_sub () {

	dig $2.$1 | awk 'c&&!--c;/;; ANSWER SECTION:/{c=1}' | awk -v subdom=$2 '{ print "The subdomain " subdom " is a " $4 " record and points to " $5}'

	return 0
}

dom_only () {

	subdomains=("www" "lb-01" "web-01" "web-02")
		
	for subdomain in "${subdomains[@]}"
	do
		dig $subdomain.$1 | awk 'c&&!--c;/;; ANSWER SECTION:/{c=1}' | awk -v subdom="$subdomain" '{ print "The subdomain " subdom " is a " $4 " record and points to " $5}'
	done

	return 0
}

# determine how many args passed
if [ -z $2 ]
then
	dom_only "$1"
else
	dom_and_sub "$1" "$2"
fi
