#!/usr/bin/env bash
# Requirements:
	# Install nginx on your web-01
	# Nginx should be listening on port 80
	# When querying Nginx at its root / with a GET request 
	#(requesting a page) using curl, it must return a page 
	# that contains the string Hello World!
	# You can’t use systemctl for restarting nginx

sudo apt-get -y update
sudo apt-get -y install nginx

mkdir -p /var/www/html
echo "Hello World!" |sudo tee  /var/www/html/index.html
sudo service nginx restart
