#!/usr/bin/env bash
# duplicate web-01 to web-02
# these scripts are an upgrade from the web-server scripts...

# uncomment to see the script run in action
#set -x
apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World"> /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page"> /etc/nginx/html/404.html
printf %s "server {
listen 80;
listen[::]:80 default_server;
add_header X-Served-By $HOSTNAME;

root /etc/nginx/html;
index index.html index.htm;
location /redirect_me{
return 301 http://cuberule.com/;
}
error_page 404 /404.html;
location /404 {
root /etc/nginx/html;
internal;
}
}" > /etc/nginx/sites-available/default
srvice nginx restart
