#!/usr/bin/env bash
# Install and configure HAProxy load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy=2.6.\*

# Config load balancer with web servers
cfg=\
"frontend load_balancer
	bind *:80
	mode http
	default_backend web_servers
backend web_servers
	balance roundrobin
	server 313915-web-01 54.234.77.65 check
	server 313915-web-02 100.25.30.149 check
"
	
echo "$cfg" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable load balancer
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy retart
