#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs
# configures a server to listening on port 80 of all server's active IPv4 IPs

sudo sed -i "s/8080/80/" /etc/nginx/nginx.conf
sudo service nginx restart
